version: '3.4'
services:
  db:
    image: dhecastro90/mysql-person-restful-crud
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: person-restful-crud
    ports:
      - "3308:3306"
    networks:
      - person-restful-network
  person-restful-crud:
    image: dhecastro90/person-restful-crud
    restart: always
    build: ./person-restful-crud
    working_dir: /person-restful-crud
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    volumes:
      - ./person-restful-crud:/person-restful-crud
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks:
      - person-restful-network
networks:
    person-restful-network:
        driver: bridge